import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()
const read = (path: string) => readFileSync(join(root, path), 'utf8')
const readIfExists = (path: string) => existsSync(join(root, path)) ? read(path) : ''
const optionalFiles = new Set([
  'src/components/group-badge.tsx',
  'src/components/model-group-selector.tsx',
  'src/features/keys/components/api-key-group-combobox.tsx',
  'src/features/system-settings/models/group-ratio-form.tsx',
  'src/features/system-settings/models/group-ratio-visual-editor.tsx',
  'src/features/system-settings/models/group-special-usable-editor.tsx',
  'src/features/system-settings/request-limits/rate-limit-visual-editor.tsx',
  'src/features/system-settings/request-limits/rate-limit-dialog.tsx',
])

const businessForbidden = [
  'cross_group_retry',
  'default_use_auto_group',
  'GroupRatio',
  'GroupGroupRatio',
  'UserUsableGroups',
  'TopupGroupRatio',
  'AutoGroups',
  'ModelRequestRateLimitGroup',
  'include_using_group',
  'using_group',
  'upgrade_group',
  'enable_groups',
  'user_group',
  'request_group',
  '/api/group',
  '/api/user/self/groups',
  "group_by: 'group'",
  "groupBy: 'group'",
  'group_ratio',
  'user_group_ratio',
  "value: 'group'",
  'usageAnalytics.groupBy.group',
  'Add group',
  'User group',
  'Groups filter',
  'Pricing by Group',
  '分组倍率',
  '升级分组',
]

describe('business group removal in default frontend', () => {
  it('removes business group contracts from feature source', () => {
    const files = [
      'src/features/keys/types.ts',
      'src/features/users/api.ts',
      'src/features/users/types.ts',
      'src/features/users/lib/user-form.ts',
      'src/routes/_authenticated/users/index.tsx',
      'src/lib/api.ts',
      'src/components/profile-dropdown.tsx',
      'src/components/layout/components/mobile-drawer.tsx',
      'src/features/profile/components/profile-header.tsx',
      'src/features/profile/types.ts',
      'src/features/wallet/types.ts',
      'src/components/group-badge.tsx',
      'src/components/model-group-selector.tsx',
      'src/features/keys/components/api-key-group-combobox.tsx',
      'src/features/channels/api.ts',
      'src/features/channels/types.ts',
      'src/features/channels/lib/channel-form.ts',
      'src/features/channels/components/drawers/channel-mutate-drawer.tsx',
      'src/features/channels/components/channels-columns.tsx',
      'src/features/channels/components/dialogs/edit-tag-dialog.tsx',
      'src/features/channels/components/dialogs/upstream-update-dialog.tsx',
      'src/routes/_authenticated/channels/index.tsx',
      'src/features/models/types.ts',
      'src/features/models/lib/model-form.ts',
      'src/features/models/components/models-columns.tsx',
      'src/features/models/components/dialogs/upstream-conflict-dialog.tsx',
      'src/features/models/components/drawers/model-mutate-drawer.tsx',
      'src/features/system-settings/types.ts',
      'src/features/system-settings/billing/index.tsx',
      'src/features/system-settings/billing/section-registry.tsx',
      'src/features/system-settings/models/index.tsx',
      'src/features/system-settings/models/ratio-settings-card.tsx',
      'src/features/system-settings/models/group-ratio-form.tsx',
      'src/features/system-settings/models/group-ratio-visual-editor.tsx',
      'src/features/system-settings/models/group-special-usable-editor.tsx',
      'src/features/system-settings/request-limits/rate-limit-section.tsx',
      'src/features/system-settings/security/index.tsx',
      'src/features/system-settings/security/section-registry.tsx',
      'src/features/system-settings/general/channel-affinity/types.ts',
      'src/features/system-settings/general/channel-affinity/api.ts',
      'src/features/system-settings/general/channel-affinity/constants.ts',
      'src/features/system-settings/general/channel-affinity/index.tsx',
      'src/features/system-settings/general/channel-affinity/rule-editor-dialog.tsx',
      'src/features/system-settings/general/channel-affinity/cache-stats-dialog.tsx',
      'src/features/subscriptions/types.ts',
      'src/features/subscriptions/api.ts',
      'src/features/subscriptions/lib/plan-form.ts',
      'src/features/subscriptions/components/subscriptions-columns.tsx',
      'src/features/subscriptions/components/subscriptions-mutate-drawer.tsx',
      'src/features/subscriptions/components/dialogs/subscription-purchase-dialog.tsx',
      'src/features/wallet/components/subscription-plans-card.tsx',
      'src/features/playground/api.ts',
      'src/features/playground/constants.ts',
      'src/features/playground/types.ts',
      'src/features/playground/index.tsx',
      'src/features/playground/components/playground-input.tsx',
      'src/features/playground/hooks/use-playground-state.ts',
      'src/features/playground/hooks/use-chat-handler.ts',
      'src/features/playground/lib/payload-builder.ts',
      'src/features/pricing/index.tsx',
      'src/features/pricing/types.ts',
      'src/features/pricing/api.ts',
      'src/features/pricing/columns.ts',
      'src/features/pricing/search.ts',
      'src/features/pricing/hooks/use-pricing-data.ts',
      'src/features/pricing/hooks/use-filters.ts',
      'src/features/pricing/lib/filters.ts',
      'src/features/pricing/lib/price.ts',
      'src/features/pricing/lib/dynamic-price.ts',
      'src/features/pricing/lib/model-helpers.ts',
      'src/features/pricing/lib/mock-stats.ts',
      'src/features/pricing/components/pricing-sidebar.tsx',
      'src/features/pricing/components/pricing-toolbar.tsx',
      'src/features/pricing/components/pricing-columns.tsx',
      'src/features/pricing/components/model-card.tsx',
      'src/features/pricing/components/model-details.tsx',
      'src/features/pricing/components/model-details-api.tsx',
      'src/features/pricing/components/model-details-performance.tsx',
      'src/routes/pricing/index.tsx',
      'src/routes/pricing/$modelId/index.tsx',
      'src/features/usage-logs/types.ts',
      'src/features/usage-logs/api.ts',
      'src/features/usage-logs/index.tsx',
      'src/features/usage-logs/lib/format.ts',
      'src/features/usage-logs/components/common-logs-filter-bar.tsx',
      'src/features/usage-logs/components/usage-logs-table.tsx',
      'src/features/usage-logs/components/columns/common-logs-columns.tsx',
      'src/features/usage-logs/components/dialogs/details-dialog.tsx',
      'src/features/usage-logs/components/dialogs/user-info-dialog.tsx',
      'src/routes/_authenticated/usage-logs/$section.tsx',
      'src/features/performance-metrics/types.ts',
      'src/features/performance-metrics/api.ts',
      'src/features/performance-metrics/lib/format.ts',
      'src/features/usage-analytics/types.ts',
      'src/features/usage-analytics/api.ts',
      'src/features/usage-analytics/constants.ts',
      'src/features/usage-analytics/index.tsx',
      'src/features/usage-analytics/components/usage-analytics-filter-bar.tsx',
      'src/features/usage-analytics/components/usage-ranking-table.tsx',
      'src/features/usage-analytics/components/usage-breakdown-chart.tsx',
      'src/features/usage-analytics/components/usage-trend-chart.tsx',
      'src/features/usage-analytics/lib/filters.ts',
      'src/features/usage-analytics/lib/chart-data.ts',
      'src/features/usage-analytics/lib/page-contract.ts',
      'src/features/admin-analytics/types.ts',
      'src/features/admin-analytics/api.ts',
      'src/features/admin-analytics/constants.ts',
      'src/features/admin-analytics/index.tsx',
      'src/features/admin-analytics/lib/filters.ts',
      'src/features/admin-analytics/lib/drilldown.ts',
      'src/features/admin-analytics/lib/chart-data.ts',
      'src/features/admin-analytics/lib/page-contract.ts',
    ]
    for (const path of files) {
      if (!optionalFiles.has(path)) assert.equal(existsSync(join(root, path)), true, `${path} must exist and be scanned`)
      const source = optionalFiles.has(path) ? readIfExists(path) : read(path)
      for (const term of businessForbidden) {
        assert.equal(source.includes(term), false, `${path} still contains ${term}`)
      }
    }

    for (const removedPath of [
      'src/features/keys/components/api-key-group-combobox.tsx',
    ]) {
      assert.equal(existsSync(join(root, removedPath)), false, `${removedPath} should be deleted`)
    }
  })
})
